// Centralized query key factory — keep all keys here so invalidation is consistent.
export const qk = {
  auth: {
    me: ['auth', 'me'],
  },
  users: {
    all: ['users'],
    list: (params) => ['users', 'list', params],
    detail: (id) => ['users', 'detail', id],
    progress: (id) => ['users', 'progress', id],
  },
  teams: {
    all: ['teams'],
    list: ['teams', 'list'],
    mine: ['teams', 'mine'],
    detail: (id) => ['teams', 'detail', id],
    progress: (id) => ['teams', 'progress', id],
  },
  classes: {
    all: ['classes'],
    list: (params) => ['classes', 'list', params],
    courses: ['classes', 'courses'],
    detail: (id) => ['classes', 'detail', id],
  },
  schedules: {
    all: ['schedules'],
    list: (params) => ['schedules', 'list', params],
    availability: (params) => ['schedules', 'availability', params],
    detail: (id) => ['schedules', 'detail', id],
    myClass: ['schedules', 'my-class'],
    attendanceCalendar: ['schedules', 'attendance-calendar'],
    config: ['schedules', 'config'],
  },
  attendance: {
    all: ['attendance'],
    bySchedule: (id) => ['attendance', 'schedule', id],
    byUser: (id) => ['attendance', 'user', id],
    analyticsByEmployee: (params) => ['attendance', 'analytics', 'employee', params],
    analyticsByTeam: (params) => ['attendance', 'analytics', 'team', params],
    analyticsByClass: (params) => ['attendance', 'analytics', 'class', params],
    myStats: ['attendance', 'my-stats'],
  },
  enrollments: {
    all: ['enrollments'],
    list: (params) => ['enrollments', 'list', params],
    byTeam: (teamId, params) => ['enrollments', 'team', teamId, params],
    byUser: (userId) => ['enrollments', 'user', userId],
  },
  evaluations: {
    all: ['evaluations'],
    list: (params) => ['evaluations', 'list', params],
    detail: (id) => ['evaluations', 'detail', id],
  },
  learning: {
    all: ['learning'],
    programs: (params) => ['learning', 'programs', params],
    program: (id) => ['learning', 'program', id],
    cohorts: (params) => ['learning', 'cohorts', params],
    cohort: (id) => ['learning', 'cohort', id],
    enrollments: (params) => ['learning', 'enrollments', params],
    feedback: (params) => ['learning', 'feedback', params],
    completionReport: (cohortId) => ['learning', 'completion-report', cohortId],
    completionRollup: ['learning', 'completion-rollup'],
    complianceReport: (params) => ['learning', 'compliance-report', params],
    paths: (params) => ['learning', 'paths', params],
    path: (id) => ['learning', 'path', id],
    pathProgress: (id) => ['learning', 'path-progress', id],
    assignments: (params) => ['learning', 'assignments', params],
    assignment: (id) => ['learning', 'assignment', id],
  },
  assessment: {
    all: ['assessment'],
    assessments: (params) => ['assessment', 'assessments', params],
    assessment: (id) => ['assessment', 'assessment', id],
    questionBank: (params) => ['assessment', 'question-bank', params],
    attempts: (params) => ['assessment', 'attempts', params],
  },
  org: {
    all: ['org'],
    departments: (params) => ['org', 'departments', params],
    myTeam: ['org', 'my-team'],
  },
  dashboard: {
    stats: ['dashboard', 'stats'],
  },
  sync: {
    status: ['sync', 'status'],
  },
  exportHr: {
    stats: ['export', 'stats'],
  },
  search: {
    global: (q) => ['search', 'global', q],
  },
};
