// Centralized query key factory — keep all keys here so invalidation is consistent.
export const qk = {
  auth: {
    me: ['auth', 'me'],
  },
  customFields: {
    all: ['custom-fields'],
    list: (params) => ['custom-fields', 'list', params],
  },
  users: {
    all: ['users'],
    list: (params) => ['users', 'list', params],
    detail: (id) => ['users', 'detail', id],
    progress: (id) => ['users', 'progress', id],
  },
  teams: {
    all: ['teams'],
    list: ['teams', 'list'],
    mine: ['teams', 'mine'],
    detail: (id) => ['teams', 'detail', id],
    progress: (id) => ['teams', 'progress', id],
  },
  classes: {
    all: ['classes'],
    list: (params) => ['classes', 'list', params],
    courses: ['classes', 'courses'],
    detail: (id) => ['classes', 'detail', id],
  },
  schedules: {
    all: ['schedules'],
    list: (params) => ['schedules', 'list', params],
    availability: (params) => ['schedules', 'availability', params],
    detail: (id) => ['schedules', 'detail', id],
    myClass: ['schedules', 'my-class'],
    // Callable for world-scoped variants (English-class separation):
    // call with no params for the base prefix (also used for invalidation).
    attendanceCalendar: (params) =>
      params ? ['schedules', 'attendance-calendar', params] : ['schedules', 'attendance-calendar'],
    config: ['schedules', 'config'],
    myWaitlist: ['schedules', 'waitlist', 'mine'],
    waitlist: (id) => ['schedules', 'waitlist', id],
  },
  attendance: {
    all: ['attendance'],
    bySchedule: (id) => ['attendance', 'schedule', id],
    byUser: (id) => ['attendance', 'user', id],
    analyticsByEmployee: (params) => ['attendance', 'analytics', 'employee', params],
    analyticsByTeam: (params) => ['attendance', 'analytics', 'team', params],
    analyticsByClass: (params) => ['attendance', 'analytics', 'class', params],
    myStats: ['attendance', 'my-stats'],
  },
  enrollments: {
    all: ['enrollments'],
    list: (params) => ['enrollments', 'list', params],
    byTeam: (teamId, params) => ['enrollments', 'team', teamId, params],
    byUser: (userId) => ['enrollments', 'user', userId],
  },
  evaluations: {
    all: ['evaluations'],
    list: (params) => ['evaluations', 'list', params],
    detail: (id) => ['evaluations', 'detail', id],
    roster: (classId) => ['evaluations', 'roster', classId],
  },
  learning: {
    all: ['learning'],
    programs: (params) => ['learning', 'programs', params],
    program: (id) => ['learning', 'program', id],
    cohorts: (params) => ['learning', 'cohorts', params],
    cohort: (id) => ['learning', 'cohort', id],
    enrollments: (params) => ['learning', 'enrollments', params],
    myEnrollments: ['learning', 'enrollments', 'mine'],
    feedback: (params) => ['learning', 'feedback', params],
    // Per-learner completion checklist + certificates (Cohesion P1).
    completion: (params) => ['learning', 'completion', params],
    certificates: (params) => ['learning', 'certificates', params],
    completionReport: (cohortId) => ['learning', 'completion-report', cohortId],
    completionRollup: ['learning', 'completion-rollup'],
    complianceReport: (params) => ['learning', 'compliance-report', params],
    paths: (params) => ['learning', 'paths', params],
    path: (id) => ['learning', 'path', id],
    pathProgress: (id) => ['learning', 'path-progress', id],
    assignments: (params) => ['learning', 'assignments', params],
    assignment: (id) => ['learning', 'assignment', id],
    myAssignments: ['learning', 'assignments', 'mine'],
    dashboardOperational: (params) => ['learning', 'dashboard', 'operational', params],
    dashboardExecutive: (params) => ['learning', 'dashboard', 'executive', params],
    dashboardSetup: ['learning', 'dashboard', 'setup'],
    dashboardDepartments: (window) => ['learning', 'dashboard', 'departments', window],
    costConfig: ['learning', 'dashboard', 'cost-config'],
    sessions: (params) => ['learning', 'sessions', params],
    reportPresets: ['learning', 'report-presets'],
  },
  assessment: {
    all: ['assessment'],
    assessments: (params) => ['assessment', 'assessments', params],
    assessment: (id) => ['assessment', 'assessment', id],
    questionBank: (params) => ['assessment', 'question-bank', params],
    attempts: (params) => ['assessment', 'attempts', params],
    myResults: ['assessment', 'results', 'mine'],
    gradingQueue: ['assessment', 'grading-queue'],
  },
  org: {
    all: ['org'],
    departments: (params) => ['org', 'departments', params],
    offices: (params) => ['org', 'offices', params],
    myTeam: ['org', 'my-team'],
  },
  rooms: {
    all: ['rooms'],
    list: (params) => ['rooms', 'list', params],
  },
  dashboard: {
    stats: ['dashboard', 'stats'],
  },
  sync: {
    status: ['sync', 'status'],
  },
  exportHr: {
    stats: ['export', 'stats'],
  },
  search: {
    global: (q) => ['search', 'global', q],
  },
  notifications: {
    all: ['notifications'],
    mine: ['notifications', 'mine'],
    preferences: ['notifications', 'preferences'],
  },
  englishTraining: {
    all: ['english-training'],
    overview: ['english-training', 'overview'],
    cohorts: ['english-training', 'cohorts'],
    classDetail: (id) => ['english-training', 'cohorts', id, 'detail'],
    courses: ['english-training', 'courses'],
    employees: (params) => ['english-training', 'employees', params],
    sessions: (params) => ['english-training', 'sessions', params],
    sessionAttendance: (id) => ['english-training', 'sessions', id, 'attendance'],
    eligibility: (params) => ['english-training', 'eligibility', params],
    issues: ['english-training', 'issues'],
    issueDetails: (code) => ['english-training', 'issues', code],
    courseRun: (id) => ['english-training', 'course-runs', id],
    levels: ['english-training', 'levels'],
    pendingExamEntries: ['english-training', 'pending-exam-entries'],
  },
  englishOperations: {
    all: ['english-operations'],
    overview: ['english-operations', 'overview'],
    learners: (params) => ['english-operations', 'learners', params],
    programs: ['english-operations', 'programs'],
    classes: ['english-operations', 'classes'],
    roster: (cohortId) => ['english-operations', 'classes', cohortId, 'roster'],
    teachers: ['english-operations', 'teachers'],
    sessions: (cohortIds) => ['english-operations', 'sessions', cohortIds],
    session: (sessionId) => ['english-operations', 'session', sessionId],
    attendance: (sessionId) => ['english-operations', 'attendance', sessionId],
    eligibility: (cohortId) => ['english-operations', 'eligibility', cohortId],
    evaluations: (cohortId) => ['english-operations', 'evaluations', cohortId],
    archiveStatus: ['english-operations', 'archive', 'status'],
    archiveSessions: ['english-operations', 'archive', 'sessions'],
    archiveSessionAttendance: (id) => ['english-operations', 'archive', 'sessions', id, 'attendance'],
    canonicalSessions: ['english-operations', 'canonical-sessions'],
    canonicalCourseRuns: ['english-operations', 'canonical-course-runs'],
    canonicalAttendance: (courseRunId, sessionUnitId) => ['english-operations', 'canonical-attendance', courseRunId, sessionUnitId],
    combinedHistory: ['english-operations', 'archive', 'combined-history'],
  },
  branding: {
    config: ['branding', 'config'],
  },
};
